import type { ComponentType } from "react"
import type { IconProps } from "@phosphor-icons/react"
import {
  AirplaneInFlight,
  AirplaneTilt,
  ArrowLeft,
  ArrowRight,
  Briefcase,
  Buildings,
  CalendarBlank,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUp,
  ChartLineUp,
  ChatCircleText,
  ChatCenteredText,
  ChatsCircle,
  Check,
  Circle,
  ClockAfternoon,
  DotsSixVertical,
  DotsThree,
  DownloadSimple,
  EnvelopeSimple,
  FacebookLogo,
  FileText,
  GlobeHemisphereEast,
  GraduationCap,
  Headset,
  Heart,
  InstagramLogo,
  Lightning,
  List,
  MagnifyingGlass,
  MapPin,
  Medal,
  Minus,
  PhoneCall,
  Play,
  Quotes,
  Shield,
  SidebarSimple,
  Star,
  Trophy,
  UploadSimple,
  UsersThree,
  UserCircle,
  WarningCircle,
  Wrench,
  X,
  YoutubeLogo,
} from "@phosphor-icons/react"

export const iconDefaults: IconProps = {
  weight: "duotone",
}

type IconRenderer = (props?: Partial<IconProps>) => JSX.Element

const withDefaults = (Component: ComponentType<IconProps>): IconRenderer => (props = {}) =>
  <Component {...iconDefaults} {...props} />

export const Icons = {
  plane: withDefaults(AirplaneTilt),
  route: withDefaults(AirplaneInFlight),
  calendar: withDefaults(CalendarBlank),
  check: withDefaults(Check),
  download: withDefaults(DownloadSimple),
  award: withDefaults(Medal),
  clock: withDefaults(ClockAfternoon),
  users: withDefaults(UsersThree),
  briefcase: withDefaults(Briefcase),
  headset: withDefaults(Headset),
  upload: withDefaults(UploadSimple),
  file: withDefaults(FileText),
  graduation: withDefaults(GraduationCap),
  phone: withDefaults(PhoneCall),
  mapPin: withDefaults(MapPin),
  envelope: withDefaults(EnvelopeSimple),
  shield: withDefaults(Shield),
  wrench: withDefaults(Wrench),
  chat: withDefaults(ChatsCircle),
  message: withDefaults(ChatCircleText),
  messageSquare: withDefaults(ChatCenteredText),
  star: withDefaults(Star),
  quote: withDefaults(Quotes),
  trend: withDefaults(ChartLineUp),
  bolt: withDefaults(Lightning),
  user: withDefaults(UserCircle),
  trophy: withDefaults(Trophy),
  heart: withDefaults(Heart),
  arrowRight: withDefaults(ArrowRight),
  arrowLeft: withDefaults(ArrowLeft),
  menu: withDefaults(List),
  close: withDefaults(X),
  chevronDown: withDefaults(CaretDown),
  chevronLeft: withDefaults(CaretLeft),
  chevronRight: withDefaults(CaretRight),
  chevronUp: withDefaults(CaretUp),
  circle: withDefaults(Circle),
  more: withDefaults(DotsThree),
  grip: withDefaults(DotsSixVertical),
  minus: withDefaults(Minus),
  play: withDefaults(Play),
  search: withDefaults(MagnifyingGlass),
  sidebar: withDefaults(SidebarSimple),
  alert: withDefaults(WarningCircle),
  alertCircle: withDefaults(WarningCircle),
  facebook: withDefaults(FacebookLogo),
  instagram: withDefaults(InstagramLogo),
  youtube: withDefaults(YoutubeLogo),
  building: withDefaults(Buildings),
  globe: withDefaults(GlobeHemisphereEast),
} as const satisfies Record<string, IconRenderer>